version: '3'
services:
  app:
    build:
        context: .
        dockerfile: Dockerfile
#    environment:
#      - REDIS_PASSWORD=<redis-password>
#      - MYSQL_PASSWORD=<mysql-password>
    ports:
      - "8080:8080"
